language: cpp
compiler:
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.5

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libsdl2-dev cppcheck
  
script: make

notifications:
  email: false
 
