language: cpp
compiler:
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - clang-3.6

before_install:
  - sudo add-apt-repository -y 'ppa:zoogie/sdl2-snapshots'
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libsdl2-dev cppcheck
  
script: make

notifications:
  email: false
 
